name: Complete Workflow

on: ['push']

jobs:

  build:

    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]
    # os passos
    steps: 
      #baixar o codigo
    - uses: actions/checkout@v2
    - run: get fetch --prune --unshallow
    
    # definir o node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Start mongo
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - name: Install Depedencies
      run: yarn --frozen-lockfile

    - name: Run all tests
      run: yarn test